name: CI-build-and-push-image-for-dockerhub

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4        

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./VariaveisAmbiente/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/variavelambiente:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/variavelambiente:${{github.ref_name }}
            ghcr.io/${{ github.repository}}:latest
            ghcr.io/${{ github.repository }}:${{github.ref_name }}  
    