name: CI-build-and-push-image-for-dotnetapp

on:
  push:
    # branches: [ main ]
    tags: ['*']
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  # pull_request:
  #   branches: [ main ]
  #   paths-ignore:
  #     - README.md
  #     - .vscode/**
  #     - .gitignore
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3        

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Increment version from repository's tags
        id: tages_versioning
        uses: georgeneto/tags-versioning
        with:
          repo-token: ${{secrets.GB_TOKEN}}
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./VariaveisAmbiente/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/variavelambiente:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/variavelambiente:${{ steps.version.outputs.next }}
